### ISSUE TITLE
Задание 4.2

### ISSUE THREAD

**Issue by E1izabeth** [Rid0n/LabITMO#2]
Не нашла. Сделайте это задание, пожалуйста. Оно обязательное.

**Comment by E1izabeth** [comment]
1) Выводится просто наибольшее число. Нужно учитывать, что оно должно появляться более одного раза. Например, в следующем примере выводится 5, тогда как должно выводиться 1.
```
Morning! What is number of rows your array has?
3
Enter every row one by one
Please enter array elements separated by a space
1 2 3 4 5
Please enter array elements separated by a space
0 0 0 0 0
Please enter array elements separated by a space
1 0 0 0 0 0
Number of Empty rows: 1
Largest number appearing more than once: 5
```
2) Есть два типа массивов [ ][ ] - массивы массивов и [ , ] - многомерные массивы. Вы используете первые и при некорректном вводе получается не матрица. Следует добавить ограничение на количество столбцов при считывании массива. Оно должно быть одинаковое для всех строк.

**Comment by Rid0n** [comment]
Спасибо! Я поправил, сейчас должно работать.
